-- The Remotion composition (remotion/VideoAgentComposition.tsx) plays a
-- scene's avatar clip for min(avatar_clip_duration_seconds, sceneSeconds),
-- then fills the remainder of the scene with B-roll. This was previously a
-- single global constant (AVATAR_CLIP_SECONDS = 3s, matching DomoAI's
-- per-request cap). The edit-screen's per-scene avatar regeneration
-- (src/trigger/regenerate-video-agent-scene-avatar.ts) can produce clips up
-- to 5s, so the on-screen duration now needs to be tracked per scene rather
-- than assumed. Default of 3 preserves today's render output for every
-- existing scene generated by the original full-pipeline task.
ALTER TABLE public.video_agent_scenes ADD COLUMN avatar_clip_duration_seconds numeric NOT NULL DEFAULT 3;
